# Generated by Django 5.2.5 on 2025-08-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredient_is_allergen_ingredient_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_allergen',
            field=models.BooleanField(default=False),
        ),
    ]
