# Generated by Django 5.2.5 on 2025-08-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='recipes'),
        ),
    ]
