# Generated by Django 5.2.5 on 2025-08-29 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='loved_by',
            field=models.ManyToManyField(blank=True, related_name='loved_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
